kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devops
nodes:
  - role: control-plane
    image: kindest/node:v1.29.7   
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080          
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
